RREF (Gauss-Jordan Elimination)


In [1]:
import numpy as np

define row elementary row operations

In [16]:
A = np.array([[1,2,3],[2,4,1],[3,4,5]])
print(A)
A.size

[[1 2 3]
 [2 4 1]
 [3 4 5]]


9

In [17]:
def switch_row(A, i, j):
  B = A.copy()
  B[[i, j], :] = B[[j, i], :]
  A = B

  return A

print(switch_row(A,0,1))

[[2 4 1]
 [1 2 3]
 [3 4 5]]


In [10]:
def switch_row(A, i, j):
  B = A.copy()
  B[[i, j], :] = B[[j, i], :]
  A = B

  return A

def scale_row(A, i, scalar):
  if scalar == 0:
    raise ValueError("Cannot scale a row by zero")
  else:
    @@@@@@
  return A

def add_scaled_row(A, target, source, scalar):
  @@@@@@
  return A

SyntaxError: invalid syntax (1034006235.py, line 2)

check elementary row operation works well

In [ ]:
A = np.array([[2, -1, 3, -1], [1, 0, 2, 1], [1, -1, 1, -2]], float)
B = switch_row(A, 1,2)
C = scale_row(A, 3)
D = add_scaled_row(A, 1, 1, 2)

1. Define variables

In [ ]:
def GJ(matrix):

  # 불러온 matrix값은 matrix 여야 함 (i.e., 2D array여야 함)
  if @@@@@@:
    raise ValueError(f"Input must be a 2D array (matrix), but got {@@@@@@@@}D.")

  pivot_i = 0 # 찾은 pivot 개수
  n_rows  = @@@@ # 주어진 matrix 의 row 수
  n_cols = @@@@ # 주어진 marix의 column 수
  rref_history = [matrix.copy()] # row operation 할 때마다 history로 저장
  n_row_operations = 0  # RREF 만들때까지 몇 번의 row operation 했는지 count

2.  column 에서 pivot 찾기, nonzero element 가 없으면, 다음 column으로, 찾았으면 pivot_i 번째 row 와 row switch

In [ ]:
def GJ(matrix):

  # 불러온 matrix값은 matrix 여야 함 (i.e., 2D array여야 함)
  if @@@@@:
    raise ValueError(f"Input must be a 2D array (matrix), but got {@@@@}D.")

  pivot_i = 0 # 찾은 pivot 개수
  n_rows  = @@@@ # 주어진 matrix 의 row 수
  n_cols = @@@@ # 주어진 marix의 column 수
  rref_history = [matrix.copy()] # row operation 할 때마다 history로 저장
  n_row_operations = 0  # RREF 만들때까지 몇 번의 row operation 했는지 count

  ################################################
  for cols in range(n_cols):
    if @@@: # column 이 row 보다 많을 때, 가능한 pivot 수에 따라서 다음 column은 조사할 필요 없음.
      break

    # column 안에 nonzero element 있는지 확인 (np.nonzero)
    non_zero_order = @@@@@
    if @@@@@: # nonzero element가 없으면 다음 column으로
      continue

    elif @@@@: # nonzero element가 있으면 row 위치 switch, (*스위치를 꼭 해야하는 것은 아님)
      matrix = switch_row(matrix, @@@@, @@@@)

      ### row operation 하였으면 다음과 같이 history와 row operation count 추가
      n_row_operations = n_row_operations + 1
      rref_history.append(matrix.copy())


3. 찾은 pivot 이 1이 되도록 scaling

In [ ]:
    matrix = scale_row(matrix, @@@@, @@@@)

    ### elementary row operation 하였으면 다음과 같이 history와 row operation count 추가
    n_row_operations = n_row_operations+1
    rref_history.append(matrix.copy())

4. pivot의 위 아래가 0이 되도록

In [ ]:
    for rows in range(n_rows):
      if @@@@@: # pivot 순서의 row 에 대해서는 계산할 필요없음.
        continue
      elif @@@@@: # 이미 element 가 0 이면 해당 row 에 대해서는 row operation 할 필요 없음
        continue
      else:
        matrix = add_scaled_row(matrix, @@@@, @@@@, @@@@)  # pivot이 위치한 column의 element가 0이 되도록 계산
        n_row_operations = n_row_operations + 1

    rref_history.append(matrix.copy()) # 여기에서는 RREF history에 마지막 결과만 저장

5. pivot 을 찾았고 계산을 다하였으면, pivot_i +1, 최종 형태

In [ ]:
def GJ(matrix):

  # 불러온 matrix값은 matrix 여야 함 (i.e., 2D array여야 함)
  if @@@@@:
    raise ValueError(f"Input must be a 2D array (matrix), but got {@@@@}D.")

  pivot_i = 0 # 찾은 pivot 개수
  n_rows  = @@@@ # 주어진 matrix 의 row 수
  n_cols = @@@@ # 주어진 marix의 column 수
  rref_history = [matrix.copy()] # row operation 할 때마다 history를 list로 저장
  n_row_operations = 0  # RREF 만들때까지 몇 번의 row operation 했는지 count

  for cols in range(n_cols):
    if @@@@: # column 이 row 보다 많을 때, 가능한 pivot 수에 따라서 다음 column은 조사할 필요 없음.
      break

    # column 안에 nonzero element 있는지 확인 (np.nonzero)
    non_zero_order = @@@@@

    if @@@@: # nonzero element가 없으면 다음 column으로
      continue

    elif @@@@: # nonzero element가 있으면 row 위치 switch, (*스위치를 꼭 해야하는 것은 아님)
      matrix = switch_row(matrix, @@@@, @@@@)

      ### row operation 하였으면 다음과 같이 history와 row operation count 추가
      n_row_operations = n_row_operations + 1
      rref_history.append(matrix.copy())

    matrix = scale_row(matrix, @@@@, @@@@)

    ### row operation 하였으면 다음과 같이 history와 row operation count 추가
    n_row_operations = n_row_operations+1
    rref_history.append(matrix.copy())

    for rows in range(n_rows):
      if @@@@: # pivot 순서의 row 에 대해서는 계산할 필요없음.
        continue
      elif @@@@: # 이미 element 가 0 이면 해당 row 에 대해서는 row operation 할 필요 없음
        continue
      else:
        matrix = add_scaled_row(matrix, @@@@, @@@@, @@@@)  # pivot이 위치한 column의 element가 0이 되도록 계산
        n_row_operations = n_row_operations + 1

    rref_history.append(matrix.copy()) # 여기에서는 RREF history에 마지막 결과만 저장

    pivot_i = pivot_i + 1

  return matrix, rref_history, n_row_operations

결과 체크

In [ ]:
A = np.array([[2, -1, 3, -1], [1, 0, 2, 1], [1, -1, 1, -2]], float)
rref_A, history, n_row_oper = GJ(A)
print('RREF')
print(rref_A)
print('')
print(f'Total elementary operations: {n_row_oper}')
print('')

for i in range(len(history)):
  print(f"order {i} \n {history[i]} \n")

NameError: name 'np' is not defined

RREF 만드는 과정에서 사용한 elementary operation 을 통해서 역행렬 구하는 알고리즘으로 확장 가능.