
Linear Algebra Operators

+, -, *, ×(cross), ⋅ (inner product), norm, transpose, box product, inverse, det, cofactor, power series, exponential, pseudo-inverse


In [1]:
## Import packages
import numpy as np


---
Basic operation


In [2]:
A = np.array([[1, 2, 3], [1, 1, 1], [3, 2, 1]])
B = np.array([[2, 1, 2,], [1, 2, 4], [2, 1, 0]])
print(A)
print(B)

[[1 2 3]
 [1 1 1]
 [3 2 1]]
[[2 1 2]
 [1 2 4]
 [2 1 0]]


In [3]:
A+B

array([[3, 3, 5],
       [2, 3, 5],
       [5, 3, 1]])

In [4]:
A-B

array([[-1,  1,  1],
       [ 0, -1, -3],
       [ 1,  1,  1]])

In [5]:
A*B

array([[2, 2, 6],
       [1, 2, 4],
       [6, 2, 0]])

In [6]:
A@B

array([[10,  8, 10],
       [ 5,  4,  6],
       [10,  8, 14]])

In [7]:
np.matmul(A,B)

array([[10,  8, 10],
       [ 5,  4,  6],
       [10,  8, 14]])

In [8]:
u = np.array([1,2,3])
v = np.array([2,4,5])

In [9]:
u

array([1, 2, 3])

In [10]:
np.cross(u,v)

array([-2,  1,  0])

In [11]:
np.inner(u,v)

np.int64(25)

In [12]:
np.dot(u,v)

np.int64(25)

In [13]:
# np.linalg.norm(u)
np.linalg.norm(v)

np.float64(6.708203932499369)

In [14]:
# A.T
np.transpose(A)

array([[1, 1, 3],
       [2, 1, 2],
       [3, 1, 1]])

In [15]:
w = np.array([4, 2, 3,])

In [16]:
np.dot(np.cross(u,v), w)

np.int64(-6)

In [17]:
A

array([[1, 2, 3],
       [1, 1, 1],
       [3, 2, 1]])

In [18]:
A**(0.5) # elementwise multiplication

array([[1.        , 1.41421356, 1.73205081],
       [1.        , 1.        , 1.        ],
       [1.73205081, 1.41421356, 1.        ]])

In [19]:
A^(2)  ## bit xor operator

array([[3, 0, 1],
       [3, 3, 3],
       [1, 0, 3]])

In [20]:
np.linalg.matrix_power(A, 3)

array([[46, 50, 54],
       [25, 25, 25],
       [54, 50, 46]])

In [21]:
A@A

array([[12, 10,  8],
       [ 5,  5,  5],
       [ 8, 10, 12]])

In [22]:
np.linalg.det(B)

np.float64(-6.0)

In [23]:
np.linalg.inv(B)

array([[ 0.66666667, -0.33333333,  0.        ],
       [-1.33333333,  0.66666667,  1.        ],
       [ 0.5       , -0.        , -0.5       ]])

In [24]:
np.linalg.pinv(B)

array([[ 6.66666667e-01, -3.33333333e-01, -1.69295099e-16],
       [-1.33333333e+00,  6.66666667e-01,  1.00000000e+00],
       [ 5.00000000e-01, -1.17957412e-16, -5.00000000e-01]])

In [25]:
# np.linalg.inv(B)
np.linalg.pinv(B)

array([[ 6.66666667e-01, -3.33333333e-01, -1.69295099e-16],
       [-1.33333333e+00,  6.66666667e-01,  1.00000000e+00],
       [ 5.00000000e-01, -1.17957412e-16, -5.00000000e-01]])



---

Functions for programming

In [26]:
A = np.array([[2, 1, 2,], [1, 2, 4], [2, 1, 0]])
print(A)

[[2 1 2]
 [1 2 4]
 [2 1 0]]


In [27]:
index = 1
axis = 0 # axis 0: row, axis 1: column
np.delete(A, index, axis)

array([[2, 1, 2],
       [2, 1, 0]])

In [28]:
index = 2
adding = [3, 4, 5]
axis = 0
np.insert(A, index, adding, axis)


array([[2, 1, 2],
       [1, 2, 4],
       [3, 4, 5],
       [2, 1, 0]])

In [29]:
adding = [[3, 4, 5]]
axis = 0
np.append(A, adding, axis) # add at the end

array([[2, 1, 2],
       [1, 2, 4],
       [2, 1, 0],
       [3, 4, 5]])

In [30]:
A = np.random.rand(4,8)
# print(A)
# new_row =
# new_column = 10
# np.reshape(A, (new_row, new_column))
np.reshape(A, (32, -1))

array([[0.06128247],
       [0.57514438],
       [0.94980809],
       [0.63460256],
       [0.49708432],
       [0.46484036],
       [0.16541495],
       [0.71035188],
       [0.79308136],
       [0.85276978],
       [0.31628695],
       [0.41428866],
       [0.98651206],
       [0.34255411],
       [0.01797929],
       [0.39819173],
       [0.77891485],
       [0.51768049],
       [0.7002372 ],
       [0.85006626],
       [0.27957084],
       [0.31792618],
       [0.78630507],
       [0.14444644],
       [0.0851805 ],
       [0.3920612 ],
       [0.86104848],
       [0.12866344],
       [0.64181965],
       [0.52232023],
       [0.35796931],
       [0.26094135]])

In [31]:
u = np.array([1,2,3])
v = np.array([2,4,5])
w = np.array([7,2,4])
A = np.array([[1, 2, 3], [1, 1, 1], [3, 2, 1]])
print(A)

[[1 2 3]
 [1 1 1]
 [3 2 1]]


In [32]:
np.vstack([u, v, w])
np.vstack([A,A])

array([[1, 2, 3],
       [1, 1, 1],
       [3, 2, 1],
       [1, 2, 3],
       [1, 1, 1],
       [3, 2, 1]])

In [33]:
np.hstack([u, v, w])
np.hstack([A,A])

array([[1, 2, 3, 1, 2, 3],
       [1, 1, 1, 1, 1, 1],
       [3, 2, 1, 3, 2, 1]])

In [35]:
print(A)
B = np.split(A, 3, axis =0)
print(B)

[[1 2 3]
 [1 1 1]
 [3 2 1]]
[array([[1, 2, 3]]), array([[1, 1, 1]]), array([[3, 2, 1]])]


In [36]:
np.triu(A) # upper triangular

array([[1, 2, 3],
       [0, 1, 1],
       [0, 0, 1]])

In [37]:
np.tril(A) # lower triangular

array([[1, 0, 0],
       [1, 1, 0],
       [3, 2, 1]])

In [38]:
print(A)

[[1 2 3]
 [1 1 1]
 [3 2 1]]


In [39]:
np.where(A>1, A, 0)

array([[0, 2, 3],
       [0, 0, 0],
       [3, 2, 0]])

In [40]:
A = np.array([[1, 2, 3], [1, 1, 1], [3, 2, 1]])
B = np.array([[2, 1, 2,], [1, 2, 4], [2, 1, 0]])

In [41]:
# np.wehre(condition, A, B)
np.where(A>1, B, 0)
np.where(A>1, A, B)

array([[2, 2, 3],
       [1, 2, 4],
       [3, 2, 0]])

In [42]:
n_row, n_col = A.shape
print(n_row, n_col)

3 3


In [43]:
A.size

9

In [44]:
A.ndim

2

In [45]:
A.flatten()

array([1, 2, 3, 1, 1, 1, 3, 2, 1])

In [46]:
B = np.expand_dims(B, axis=0)
print(B.shape)

(1, 3, 3)


In [47]:
B = np.expand_dims(B, axis = 2)

In [48]:
B =np.squeeze(B)

In [49]:
B.shape

(3, 3)

In [66]:
print(A)

[[2 4 1]
 [3 1 1]
 [1 2 1]]


In [67]:
# A[0:2]
print(A[0:2])

[[2 4 1]
 [3 1 1]]


In [68]:
# A[-1,2]
print(A[-1:,2])

[1]


In [53]:
np.sum(A, axis = 0)

array([5, 5, 5])

In [54]:
np.zeros((1,2,1))

array([[[0.],
        [0.]]])

In [55]:
np.diag([3,5,2], 0)

array([[3, 0, 0],
       [0, 5, 0],
       [0, 0, 2]])

---
Minor, Cofactor, Adjoint matrix


In [69]:
A = np.array([[2, 4, 1,], [3, 1, 1], [1, 2, 1]])
print(A)

[[2 4 1]
 [3 1 1]
 [1 2 1]]


In [57]:
def reduce_matrix(matrix, i,j):
  new_matrix = np.delete(matrix, i, 0)
  new_matrix = np.delete(new_matrix, j, 1)
  return new_matrix

In [58]:
cofactor_matrix = np.zeros_like(A, float)

for i in range(A.shape[0]):
  for j in range(A.shape[1]):
    minor = np.linalg.det(reduce_matrix(A, i,j))
    cofactor = ((-1)**(i+j))*minor
    cofactor_matrix[i,j] = cofactor

print(cofactor_matrix)

[[ -1.  -2.   5.]
 [ -2.   1.  -0.]
 [  3.   1. -10.]]


In [59]:
adjoint_matrix = cofactor_matrix.T
inverse_matrix = 1/np.linalg.det(A) * adjoint_matrix
print(inverse_matrix)
print(np.linalg.inv(A))

[[ 0.2  0.4 -0.6]
 [ 0.4 -0.2 -0.2]
 [-1.   0.   2. ]]
[[ 0.2  0.4 -0.6]
 [ 0.4 -0.2 -0.2]
 [-1.   0.   2. ]]
